### ISSUE TITLE
Firefly camera ROI not working

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#289] opened 2024-10-28 23:40 UTC
**Describe the bug**
The ROI functionatities in Firefly camera GUI are not working. Also, the exposure time slider doesn't seem to adjust. 

**To Reproduce**
1. Open firefly
2. Open e.g., Microprobe mono Flag camera

**Expected behavior**
Should be able to put ROIs 

**Desktop (please complete the following information):**
 - LERIX computer but logged in with 25idcuser Firefly

**Comment by canismarko** [comment] 2024-10-29 00:18
Thanks @Cathyhjj . I think this is a duplicate of #232, so I'm going to close this. Feel free to reopen if I missed something.

**Closed by canismarko** 2024-10-29 00:18 UTC
